spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: tkddnjs0823
mybatis:
  mapper-locations: classpath:/sqlmap/sqlmapper_*.xml